image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            runs-on:
              - self.hosted
              - linux.shell
            caches:
              - node
            script:
              - npm install
              - npm run-script build
              - npm run-script test
        - step:
            name: Code linting
            runs-on:
              - self.hosted
              - linux.shell
            caches:
              - node
            script:
              - npm install
              - npm run-script lint
